# Generated by Django 2.0.5 on 2018-06-12 13:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('comment', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('reservation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Reservation date')),
                ('date_from', models.DateField(verbose_name='From')),
                ('date_to', models.DateField(verbose_name='To')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='Opis')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pension.Room'),
        ),
    ]
