# Generated by Django 2.0.5 on 2018-06-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0004_auto_20180612_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='surname',
            field=models.CharField(max_length=200),
        ),
    ]
